### ISSUE TITLE
bydbatt v.1.0.8

### ISSUE THREAD

**Issue by andreaskoerber** [arteck/ioBroker.bydbatt#16]
I installed "bydbatt" for a BYD LV Battery.
Installation and startup OK. All configurations, too, apart from setting "installed arrays" to 1 makes the instance stop with
error messages:

<html><body>

host.iobrokerpi | 2022-10-28 18:40:55.040 | info | Do not restart adapter system.adapter.bydbatt.0 because disabled or deleted
-- | -- | -- | --
host.iobrokerpi | 2022-10-28 18:40:55.039 | error | instance system.adapter.bydbatt.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
bydbatt.0 | 2022-10-28 18:40:54.322 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
bydbatt.0 | 2022-10-28 18:40:54.258 | error | adapter disabled
host.iobrokerpi | 2022-10-28 18:40:42.225 | info | "system.adapter.bydbatt.0" disabled
host.iobrokerpi | 2022-10-28 18:40:22.293 | info | Restart adapter system.adapter.bydbatt.0 because enabled
host.iobrokerpi | 2022-10-28 18:40:22.292 | error | instance system.adapter.bydbatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
bydbatt.0 | 2022-10-28 18:40:21.580 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
bydbatt.0 | 2022-10-28 18:40:21.572 | error | Cannot read properties of undefined (reading '1')
bydbatt.0 | 2022-10-28 18:40:21.570 | error | TypeError: Cannot read properties of undefined (reading '1')     at AxiosDigestAuth.request (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/dist/index.js:28:41)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async bydbattControll.getDatenHome (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:105:19)     at async bydbattControll.getInfos (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:78:27)     at async bydbattControll.onReady (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:52:9)
bydbatt.0 | 2022-10-28 18:40:21.569 | error | unhandled promise rejection: Cannot read properties of undefined (reading '1')
bydbatt.0 | 2022-10-28 18:40:21.567 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>

**Comment by andreaskoerber** [comment]
No one servicing this adapter?
This could all be due to settings. But whete would I find info? e.g on proper number of arrays and of "installed batteries"

**Comment by arteck** [comment]
install GIT version and check again
