### ISSUE TITLE
errors after the last update

### ISSUE THREAD

**Issue by MirkoHuf** [arteck/ioBroker.bydbatt#2]
**Describe the bug**  
Hi, i got a lot of error messages after the last update. Workes without problems since months until today.

bydbatt.0 | 2021-04-25 00:04:28.451 | info | (1435) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
bydbatt.0 | 2021-04-25 00:04:28.450 | info | (1435) terminating
bydbatt.0 | 2021-04-25 00:04:28.408 | info | (1435) cleaned everything up...
bydbatt.0 | 2021-04-25 00:04:28.408 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
bydbatt.0 | 2021-04-25 00:04:28.408 | error | at runMicrotasks (<anonymous>)
bydbatt.0 | 2021-04-25 00:04:28.408 | error | at bydbattControll.onReady (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:52:20)
bydbatt.0 | 2021-04-25 00:04:28.408 | error | at bydbattControll.getInfos (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:78:38)
bydbatt.0 | 2021-04-25 00:04:28.408 | error | at bydbattControll.getDatenHome (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:105:36)
bydbatt.0 | 2021-04-25 00:04:28.408 | error | (1435) TypeError: Cannot read property 'request' of null
bydbatt.0 | 2021-04-25 00:04:28.408 | error | (1435) unhandled promise rejection: Cannot read property 'request' of null
Unhandled | 2021-04-25 00:04:28.407 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bydbatt.0 | 2021-04-25 00:04:24.650 | error | (1435) other problem

Password and IP was double checked - that's correct.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/7764831/115974059-4a78c300-a55a-11eb-876c-c484837cd282.png)

**Versions:**  
 - Adapter version: 1.0.3
 - JS-Controller version: 3.1.6
 - Node version: 12.22.1
 - Operating system: Docker container on synology nas

**Comment by arteck** [comment]
the request is empty.. after restart the adapter also ??

**Comment by MirkoHuf** [comment]
Yes - the same.

**Comment by MirkoHuf** [comment]
Works after the last update. Thank you.

**Comment by aDabbelju** [comment]
I got the same errors like @MirkoHuf. I tried version 1.0.5 and 1.0.7, restart and a reinstall. 

 Versions:

    Adapter version: 1.0.7
    JS-Controller version: 3.2.16
    Node version: 14.16.1
    Operating system: Docker container on synology nas



![bydbatt](https://user-images.githubusercontent.com/39333466/124437620-8957a000-dd77-11eb-915f-af832a4f2d62.JPG)
