### ISSUE TITLE
No connection to Battery-Box-HV

### ISSUE THREAD

**Issue by RaigK** [arteck/ioBroker.bydbatt#6]
I tried to connect the adapter to my battery, unfortunately it stayed red. In the adapter you can set up to 8 batteries per array. But I have 9 modules (full expansion) in my BYD Battery-BOX HV.
![image](https://user-images.githubusercontent.com/3357449/117536845-bb5db780-affd-11eb-8c2d-c611884ec5fd.png)

**Comment by RaigK** [comment]
Good news, I got the adapter working. Two things I have changed. My BYD Box HV has as a fixed default user "Installer" I changed this in main.js. Also I added another line in the "index_m.html" for battery number 9.

in main.js
let PASSWORD = "";
const USERNAME = "installer";

in index_m.html
                <div class="input-field suffix col s12 m6 l4">
                    <select id="batterynum" class="value">
                        <option value="" disabled selected class="translate">batterynum</option>
                        <option value="01">01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                    </select>
                    <label for="batterynum" class="translate">batterynum</label>
                </div>

It would be nice if you could modify this for me and other users.

**Comment by RaigK** [comment]
<div class="input-field suffix col s12 m6 l4">
                    <select id="batterynum" class="value">
                        <option value="" disabled selected class="translate">batterynum</option>
                        <option value="01">01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                    </select>
                    <label for="batterynum" class="translate">batterynum</label>
                </div>

**Comment by arteck** [comment]
check now plz
![grafik](https://user-images.githubusercontent.com/6681528/118398554-723ee080-b659-11eb-84d7-9c99fb7b75f3.png)

**Comment by RaigK** [comment]
Since it is not yet possible to install version 1.05 via iobroker, I have exchanged the files manually. The adapter is green again and I can select the "installer" and 9 batteries.
![image](https://user-images.githubusercontent.com/3357449/118411001-b69aa280-b692-11eb-96ad-2c4662b99385.png)
Thank you!
