### ISSUE TITLE
Error on start with Nodsejs 14

### ISSUE THREAD

**Issue by jk-andersen** [arteck/ioBroker.bydbatt#8]
Starting a reboot-loop on Nodejs 14.
Log:

<html>
<body>

bydbatt.0 | 2021-06-28 15:01:55.715 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
bydbatt.0 | 2021-06-28 15:01:55.714 | info | terminating
bydbatt.0 | 2021-06-28 15:01:55.714 | info | cleaned everything up...
bydbatt.0 | 2021-06-28 15:01:55.713 | error | Cannot read property '1' of undefined
bydbatt.0 | 2021-06-28 15:01:55.713 | error | TypeError: Cannot read property '1' of undefined at AxiosDigestAuth.request (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/dist/index.js:28:41) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async bydbattControll.getDatenHome (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:105:19) at async bydbattControll.getInfos (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:78:27) at async bydbattControll.onReady (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:52:9)
bydbatt.0 | 2021-06-28 15:01:55.712 | error | unhandled promise rejection: Cannot read property '1' of undefined
bydbatt.0 | 2021-06-28 15:01:55.712 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bydbatt.0 | 2021-06-28 15:01:55.553 | info | starting. Version 1.0.6 in /opt/iobroker/node_modules/iobroker.bydbatt, node: v14.17.1, js-controller: 3.3.14

</body>
</html>

It connects first, but then stops. Does not read the values.
I have  BYD HVS 7.7

**Comment by arteck** [comment]
its not node14 problem.. check you settings .. is the ip correct ?

**Comment by jk-andersen** [comment]
Ok, i found the first problem - Misinterpreted the arrays.
Now it connects, stays green but then it throws errors and start a reboot loop.


<html>
<body>


host.iobroker | 2021-07-04 10:35:08.736 | error | instance system.adapter.bydbatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
bydbatt.0 | 2021-07-04 10:35:08.205 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
bydbatt.0 | 2021-07-04 10:35:08.205 | info | terminating
bydbatt.0 | 2021-07-04 10:35:08.204 | info | cleaned everything up...
bydbatt.0 | 2021-07-04 10:35:08.203 | error | Cannot read property '1' of undefined
bydbatt.0 | 2021-07-04 10:35:08.203 | error | TypeError: Cannot read property '1' of undefined at AxiosDigestAuth.request (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/dist/index.js:28:41) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async bydbattControll.getDatenHome (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:105:19) at async bydbattControll.getInfos (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:78:27) at async bydbattControll.onReady (/opt/iobroker/node_modules/iobroker.bydbatt/main.js:52:9)
bydbatt.0 | 2021-07-04 10:35:08.203 | error | unhandled promise rejection: Cannot read property '1' of undefined
bydbatt.0 | 2021-07-04 10:35:08.202 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bydbatt.0 | 2021-07-04 10:34:36.431 | info | starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.bydbatt, node: v14.17.2, js-controller: 3.3.14


</body>
</html>

**Comment by arteck** [comment]
set debug mode and check log
