### ISSUE TITLE
HVM Serie

### ISSUE THREAD

**Issue by Trunks1982** [arteck/ioBroker.bydbatt#9]
Hi ich wollte heute mal deinen Adapter ausprobieren und ich bekomme zu meinem BYD HVM Speicher keine Verbindung.Ronny hat mir schon dabei geholfen keine Chance.Es gibt noch nen anderen BYD Adapter da funktionierest sofort.Würde aber gerne mal deinen testen, weil ronny meint da sieht man jede Zelle usw.

Gruß Christoph

**Comment by arteck** [comment]
was sagt das LOG ??
